project_urls:
    Project Site: https://github.com/kevinyamauchi/napari-properties-viewer
    Report Issues: https://github.com/kevinyamauchi/napari-properties-viewer/issues
    Documentation: https://github.com/kevinyamauchi/napari-properties-viewer
    User Support: https://github.com/kevinyamauchi/napari-properties-viewer/issues